### ISSUE TITLE
thrift includes not found

### ISSUE THREAD

**Issue by adrianheine** [hhvm/hhvm-third-party#36]
Since 486597c3b2abe33de5ef249c0b13f8128dd19bf3, compilation fails for me with `thrift/lib/cpp/async/TAsyncTransport.h` not found. The files CMake generates all lack the new `src/` path component.

**Comment by jwatzman** [comment]
Yeah, this looks like an issue with upstream thrift. @denji points out that `features.h` is apparently Linux-only? https://github.com/hhvm/hhvm-third-party/pull/26 fixed that for us a while, it's possible that upstream thrift regressed. @xssworm if you're still running into this issue, please reopen it against upstream thrift -- pointing them here wrt `features.h` explanation might be useful context, but they need to fix this, and then we can update to the fixed rev.

**Comment by denji** [comment]
@jwatzman https://github.com/facebook/hhvm/issues/4444
