### ISSUE TITLE
consider becoming new maintainer for libafdt?

### ISSUE THREAD

**Issue by jrobeson** [hhvm/hhvm-third-party#47]
the upstream version of this package is basically dead.

Maybe liftafdt should be renamed libfbafdt (or something else) and then put in a separate repository.

**Comment by jrobeson** [comment]
After attempting to package libafdt for fedora, i already found that it's spewing deprecated warnings, so it will break eventually. I submitted a PR to fix that here: https://github.com/hhvm/hhvm-third-party/pull/48

**Comment by jwatzman** [comment]
Just commented about this on #48.

**Comment by jrobeson** [comment]
looks like we have a new repo libafdt. closing this.
