### ISSUE TITLE
are the curl patches here still relevant to FB?

### ISSUE THREAD

**Issue by jrobeson** [hhvm/hhvm-third-party#50]
Are these curl patches still used by anybody internally?

https://github.com/hhvm/hhvm-third-party/blob/master/libcurl-7.22.1.fb-changes.diff
https://github.com/hhvm/hhvm-third-party/blob/master/libcurl.fb-changes.diff

**Comment by jwatzman** [comment]
@sgolemon @fredemmott @paulbiss anyone know?

**Comment by JoelMarcey** [comment]
cc: @jdelong who seems to have committed the patches in 2013

**Comment by jdelong** [comment]
I think I just git mv'd them.

**Comment by jwatzman** [comment]
I don't see any references to them, internal or external. Since no one knows, and they look dead, I'd say kill them if they're in your way.

**Comment by simonwelsh** [comment]
They're mentioned in the [12.04 build instructions](https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-12.04#building-third-party-libraries). Have never needed to apply that patch on 12.04 though.

**Comment by jrobeson** [comment]
@simonwelsh : so do you think we should remove em from the instructions then?

**Comment by fredemmott** [comment]
I think this has been removed now.

**Comment by jrobeson** [comment]
no, they are still here https://github.com/hhvm/hhvm-third-party

**Comment by fredemmott** [comment]
Whoops, apparently I was thinking of libevent, sorry

**Comment by jrobeson** [comment]
So, anybody else built on ubuntu 12.0.4 and had a good experience without bothering with the patches?

**Comment by jrobeson** [comment]
@fredemmott : i submitted a PR to remove them as i don't see why one would build an old curl on purpose when trying to build such new software.  https://github.com/hhvm/hhvm-third-party/pull/59
