### ISSUE TITLE
use double-conversion as a submodule

### ISSUE THREAD

**Issue by jrobeson** [hhvm/hhvm-third-party#52]
double-conversion is now on github officially (https://github.com/floitsch/double-conversion) , so we can include it as a submodule.

It also now seems to have enhanced support for building on windows, both with cygwin and as normal.

NOTE: there are some build changes though. A cursory glance shows me that the source  directory has moved into a sub directory and the various CMake files have been expanded.

**Comment by Orvid** [comment]
Or just google/double-conversion, which is what it now points at.
