### ISSUE TITLE
git status isn't clean after a build

### ISSUE THREAD

**Issue by gdbentley** [hhvm/hhvm-third-party#97]
Commit 9f6ae51e switched from webscalesql-5.6 to mysql-5.6.git. The latter does not give a clean
git status after a build. Several non-ignored files are generated, including one which exists as a checked in file and therefore diffs. I tried submitting a fix to mysql-5.6 but it was rejected in favor of fixing upstream. I don't have a contributor agreement in place with Oracle.

**Comment by JoelMarcey** [comment]
@gdbentley I am assuming you are getting a dirty `hhvm-third-party` after building `hhvm`, right?

Have you done the following:

```
% rm -rf third-party
% git submodule init
% git submodule update --init --recursive
```

and see if you get the dirty repo?

cc: @drilibo

**Comment by jwatzman** [comment]
I'm going to have to tell you the same thing... not sure what we can do about this since we just submodule that in. `mysql-5.6` needs to have a fix, and if they don't want to take one directly, then one needs to go upstream and then into that repo.

@JoelMarcey this has nothing to do with the switchover itself.

**Comment by JoelMarcey** [comment]
Oh ok... thanks @jwatzman

**Comment by jwatzman** [comment]
BTW @JoelMarcey apologies if what I wrote above comes across as snippy/rude, wasn't my intent, but reading this thread again I realize it could have come off that way!

**Comment by gdbentley** [comment]
To be clear, I just wanted to document for others why this used to work and doesn't anymore. I like to do a git status before wiping out an hhvm development tree, and it surprised me when I started getting a dirty status.

**Comment by JoelMarcey** [comment]
@jwatzman I didn't take it that way :)
